version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        applies-to: version-updates
        patterns: ["*"]
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        applies-to: version-updates
        patterns: ["*"]
    target-branch: "main"
